"""E20: Rare-class oversampling for kNN — synthetic minority augmentation.

Idea: Before running CB-kNN, augment the rare class training set with
synthetic samples generated by interpolation (SMOTE-style) in latent space.

This addresses the core problem: with only 5 rare cells, the kNN neighborhood
is dominated by majority class cells.

Augmentation: For each rare cell, generate K_aug synthetic cells by
interpolating between the rare cell and its k nearest rare-class neighbors.

Compare: CB-kNN (no augmentation) vs CB-kNN + augmentation.

Run on: all datasets, rts=5/20/50, seed42.

Usage:
    python src/experimental/e20_rare_class_oversampling_knn.py
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import numpy as np
import pandas as pd
from collections import Counter
from sklearn.neighbors import NearestNeighbors

from utils import classification_tables, read_table, write_table
from experimental.mahalanobis_poc import (
    _latent,
    _class_prototypes,
    _euclidean,
    _pooled_covariance_shrunk,
    _mahalanobis,
    _predict_nearest,
)

ROOT = Path(__file__).resolve().parents[2]
OUT_DIR = ROOT / "outputs" / "_experimental" / "e20_rare_oversampling_knn"
OUT_DIR.mkdir(parents=True, exist_ok=True)

K_CB = 30
K_AUG = 3   # k nearest rare neighbors for interpolation
N_AUG_GRID = [5, 10, 20, 50]  # number of synthetic samples per rare cell

DATASET_CONFIGS = [
    ("outputs/immune_dc",       "cDC1",                    "batch_heldout",   "cdc1"),
    ("outputs/immune_dc",       "ASDC",                    "batch_heldout",   "asdc"),
    ("outputs/pancreas",        "epsilon",                 "batch_heldout",   "epsilon"),
    ("outputs/pancreas",        "gamma",                   "batch_heldout",   "gamma"),
    ("outputs/tabula_liver",    "non-classical monocyte",  "cell_stratified", "non-classical_monocyte"),
    ("outputs/tabula_kidney",   "endothelial cell",        "cell_stratified", "endothelial_cell"),
    ("outputs/tabula_spleen",   "innate lymphoid cell",    "batch_heldout",   "innate_lymphoid_cell"),
]

SEEDS = [42]
RTS_VALUES = [5, 20, 50]


def smote_augment(
    rare_z: np.ndarray,
    n_aug: int,
    k: int,
    rng: np.random.Generator,
) -> np.ndarray:
    """Generate synthetic rare cells by SMOTE interpolation."""
    n_rare = len(rare_z)
    if n_rare < 2:
        # Can't interpolate with 1 cell — add Gaussian noise instead
        noise = rng.normal(0, 0.1, size=(n_aug, rare_z.shape[1]))
        return rare_z[0:1] + noise

    k_eff = min(k, n_rare - 1)
    nbrs = NearestNeighbors(n_neighbors=k_eff + 1, algorithm="ball_tree")
    nbrs.fit(rare_z)
    _, nn_idx = nbrs.kneighbors(rare_z)
    # nn_idx[:, 0] is self, so use [:, 1:]
    nn_idx = nn_idx[:, 1:]

    synthetic = []
    for _ in range(n_aug):
        # Pick a random rare cell
        i = rng.integers(0, n_rare)
        # Pick a random neighbor
        j = nn_idx[i, rng.integers(0, k_eff)]
        # Interpolate
        alpha = rng.uniform(0, 1)
        synthetic.append(rare_z[i] + alpha * (rare_z[j] - rare_z[i]))

    return np.vstack(synthetic)


def cb_knn_predict(
    train_z: np.ndarray,
    train_labels: np.ndarray,
    test_z: np.ndarray,
    k: int,
    class_counts: dict[str, int],
) -> np.ndarray:
    k_eff = min(k, len(train_z))
    nbrs = NearestNeighbors(n_neighbors=k_eff, algorithm="ball_tree", n_jobs=-1)
    nbrs.fit(train_z)
    nn_dists_all, nn_idx_all = nbrs.kneighbors(test_z)
    preds = []
    eps = 1e-10
    for i in range(len(test_z)):
        nn_idx    = nn_idx_all[i]
        nn_labels = train_labels[nn_idx]
        nn_dists  = nn_dists_all[i]
        vote: dict[str, float] = {}
        for lbl, d in zip(nn_labels, nn_dists):
            n_c = class_counts.get(lbl, 1)
            w = 1.0 / (n_c * d ** 2 + eps)
            vote[lbl] = vote.get(lbl, 0.0) + w
        preds.append(max(vote, key=vote.get))
    return np.array(preds)


def run_one(run_dir: Path, rare_class: str) -> list[dict]:
    emb_dir = run_dir / "embeddings"
    if not emb_dir.exists():
        return []

    try:
        train_pred = read_table(emb_dir / "train_predictions.csv")
        train_lat  = read_table(emb_dir / "train_latent.csv")
        test_pred  = read_table(emb_dir / "test_predictions.csv")
        test_lat   = read_table(emb_dir / "test_latent.csv")
    except FileNotFoundError:
        return []

    is_labeled = train_pred["is_labeled_for_scanvi"].astype(bool).to_numpy()
    train_z = _latent(train_lat)
    test_z  = _latent(test_lat)
    y_true  = test_pred["true_label"].astype(str)

    if rare_class not in y_true.values:
        return []

    classes, protos, counts_map = _class_prototypes(train_z, train_pred["true_label"], is_labeled)
    if rare_class not in classes:
        return []

    ref_z      = train_z[is_labeled]
    ref_labels = train_pred["true_label"].astype(str).to_numpy()[is_labeled]
    class_counts = dict(Counter(ref_labels))

    name = run_dir.name
    seed = None
    rts  = None
    for part in name.split("_"):
        if part.startswith("seed"):
            try:
                seed = int(part[4:])
            except ValueError:
                pass
        if part.startswith("rare") and part != "rareall":
            try:
                rts = int(part[4:])
            except ValueError:
                pass

    rows = []

    # scANVI baseline
    scanvi_m, _ = classification_tables(y_true, test_pred["predicted_label"], rare_class=rare_class)
    rows.append({
        "run": name, "rare_class": rare_class, "seed": seed, "rts": rts,
        "method": "scANVI", "n_aug": None, "rare_f1": scanvi_m["rare_f1"],
    })

    # Euclidean
    euc_dists = _euclidean(test_z, protos)
    euc_pred  = _predict_nearest(euc_dists, classes)
    euc_m, _  = classification_tables(y_true, pd.Series(euc_pred), rare_class=rare_class)
    rows.append({
        "run": name, "rare_class": rare_class, "seed": seed, "rts": rts,
        "method": "Euclidean", "n_aug": None, "rare_f1": euc_m["rare_f1"],
    })

    # Mahal-pooled
    pooled = _pooled_covariance_shrunk(train_z, train_pred["true_label"], is_labeled, classes)
    pooled_covs = [pooled] * len(classes)
    mah_dists = _mahalanobis(test_z, protos, pooled_covs)
    mah_pred  = _predict_nearest(mah_dists, classes)
    mah_m, _  = classification_tables(y_true, pd.Series(mah_pred), rare_class=rare_class)
    rows.append({
        "run": name, "rare_class": rare_class, "seed": seed, "rts": rts,
        "method": "Mahal-pooled", "n_aug": None, "rare_f1": mah_m["rare_f1"],
    })

    # CB-kNN (no augmentation)
    cb_pred = cb_knn_predict(ref_z, ref_labels, test_z, K_CB, class_counts)
    cb_m, _ = classification_tables(y_true, pd.Series(cb_pred), rare_class=rare_class)
    rows.append({
        "run": name, "rare_class": rare_class, "seed": seed, "rts": rts,
        "method": "CB-kNN (no aug)", "n_aug": 0, "rare_f1": cb_m["rare_f1"],
    })

    # CB-kNN + SMOTE augmentation
    rare_mask = ref_labels == rare_class
    rare_z = ref_z[rare_mask]
    rng = np.random.default_rng(42)

    # Validation split for n_aug tuning
    n_test = len(test_z)
    val_rng = np.random.default_rng(99)
    val_idx = val_rng.choice(n_test, size=max(1, n_test // 5), replace=False)
    test_idx = np.setdiff1d(np.arange(n_test), val_idx)
    if len(test_idx) == 0:
        test_idx = np.arange(n_test)

    y_val = y_true.iloc[val_idx].reset_index(drop=True)

    best_n_aug = 0
    best_val_f1 = cb_m["rare_f1"]  # baseline

    for n_aug in N_AUG_GRID:
        # Generate synthetic rare cells
        synthetic_z = smote_augment(rare_z, n_aug, K_AUG, rng)
        synthetic_labels = np.array([rare_class] * n_aug)

        # Augmented training set
        aug_z = np.vstack([ref_z, synthetic_z])
        aug_labels = np.concatenate([ref_labels, synthetic_labels])
        aug_counts = dict(Counter(aug_labels))

        pred_val = cb_knn_predict(aug_z, aug_labels, test_z[val_idx], K_CB, aug_counts)
        m_val, _ = classification_tables(y_val, pd.Series(pred_val), rare_class=rare_class)
        if m_val["rare_f1"] > best_val_f1:
            best_val_f1 = m_val["rare_f1"]
            best_n_aug = n_aug

    if best_n_aug > 0:
        # Apply best n_aug to full test
        synthetic_z = smote_augment(rare_z, best_n_aug, K_AUG, rng)
        synthetic_labels = np.array([rare_class] * best_n_aug)
        aug_z = np.vstack([ref_z, synthetic_z])
        aug_labels = np.concatenate([ref_labels, synthetic_labels])
        aug_counts = dict(Counter(aug_labels))
        aug_pred = cb_knn_predict(aug_z, aug_labels, test_z, K_CB, aug_counts)
        aug_m, _ = classification_tables(y_true, pd.Series(aug_pred), rare_class=rare_class)
        rows.append({
            "run": name, "rare_class": rare_class, "seed": seed, "rts": rts,
            "method": f"CB-kNN+SMOTE(n={best_n_aug})", "n_aug": best_n_aug,
            "rare_f1": aug_m["rare_f1"],
        })
        print(f"  rts={rts:3d}  scANVI={scanvi_m['rare_f1']:.3f}  "
              f"Eucl={euc_m['rare_f1']:.3f}  Mahal={mah_m['rare_f1']:.3f}  "
              f"CB-kNN={cb_m['rare_f1']:.3f}  "
              f"CB-kNN+SMOTE(n={best_n_aug})={aug_m['rare_f1']:.3f}")
    else:
        rows.append({
            "run": name, "rare_class": rare_class, "seed": seed, "rts": rts,
            "method": "CB-kNN+SMOTE(no improvement)", "n_aug": 0,
            "rare_f1": cb_m["rare_f1"],
        })
        print(f"  rts={rts:3d}  scANVI={scanvi_m['rare_f1']:.3f}  "
              f"Eucl={euc_m['rare_f1']:.3f}  Mahal={mah_m['rare_f1']:.3f}  "
              f"CB-kNN={cb_m['rare_f1']:.3f}  "
              f"CB-kNN+SMOTE=no improvement")

    return rows


def main() -> pd.DataFrame:
    all_rows = []

    for dataset_dir, rare_class, split_prefix, rare_slug in DATASET_CONFIGS:
        dataset_path = ROOT / dataset_dir
        if not dataset_path.exists():
            continue

        dataset_name = dataset_path.name
        print(f"\n{'='*60}")
        print(f"Dataset: {dataset_name}  rare_class: {rare_class}")
        print(f"{'='*60}")

        for seed in SEEDS:
            for rts in RTS_VALUES:
                run_name = f"{split_prefix}_seed{seed}_{rare_slug}_rare{rts}"
                run_dir  = dataset_path / run_name
                if not run_dir.exists():
                    continue

                rows = run_one(run_dir, rare_class)
                for row in rows:
                    row["dataset"] = dataset_name
                all_rows.extend(rows)

    if not all_rows:
        print("No results collected!")
        return pd.DataFrame()

    df = pd.DataFrame(all_rows)
    write_table(df, OUT_DIR / "results.csv")

    print("\n\n=== E20 Summary: CB-kNN + SMOTE augmentation ===")
    pivot = df.pivot_table(
        index=["dataset", "rare_class", "rts"],
        columns="method",
        values="rare_f1",
        aggfunc="first",
    )
    print(pivot.to_string(float_format=lambda x: f"{x:.3f}"))

    return df


if __name__ == "__main__":
    main()
